name: Tests

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:

  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: pip install pre-commit~=4.1

    - name: Run pre-commit tests
      run: pre-commit run --all-files

  audit-grammar:
    name: Audit the grammar files
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - run: sudo apt install subversion
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: make audit_grammars

  audit-authors:
    name: Audit the AUTHORS list
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - run: make audit_authors

  audit-spelling:
    name: Audit spelling in the specification
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - run: make audit_spelling
